### ISSUE TITLE
Minting NFT token issue

### ISSUE THREAD

**Issue by 42zeroo** [Hashpack/hashconnect#102]
Hello!
I'm playing with hashconnect and i'm get in trouble.
Does hedera-sdk transaction modules are fully supported by HashConnect?
Is the TokenMintTransaction working well?
When i'm trying to mint NFT with
```js
 let trans = await new TokenMintTransaction()
            .setTokenId(tokenId)
            .setAmount(1);
        trans.addMetadata(new Uint8Array(Buffer.from(CID)));
// I also tried solution following Hedera's yt tutorial "How to Mint NFTs on Hedera with JavaScript pt. 1"
// https://youtu.be/lp3mwdYEZEk?t=298
// .setMetadata([Buffer.from(CID)]) 
```
with later on signing with ``supplyKey``

But with both tries im reciving ``[Object Object]`` in wallet modal, and in hashConnect.sendTransaction() method response a ``success: false``.
![screenshot_from_wallet](https://user-images.githubusercontent.com/29521242/164712463-06a2429d-efee-4578-a705-4fdf226f52a1.png)

Am I doing something wrong?
I had created before new token type non-fungible with supply type finite, initial supply set to 0 and max to 10 with no decimals. I wasnt set any custom fees. And i had created and trying to mint with the same account, which was also set as treasure account ID and auto-renew account ID.

I'm also have same issue when trying in my own example also in dApp example you have provided.

**Comment by teacoat** [comment]
Hey there, we had a bit of an error on the hashpack side not returning errors correctly, this should be fixed now!
