### ISSUE TITLE
HashConnectSigner not compatible with hethers Signer

### ISSUE THREAD

**Issue by dragoonzx** [Hashpack/hashconnect#108]
Error: invalid signer or provider

wen using with hethers.Contract

**Comment by dragoonzx** [comment]
> @dragoonzx have you found any solution?

Hi, I dont remember exactly. I think its better to use @hashgraph/sdk, thats what I did. Maybe you can find answers in their source code, I dont know whether its open-source or not

**Comment by moshenskyDV** [comment]
For those one who faced this issue:
Currently you won't be able to use Hethers with HashPack properly.

If you want to sign transaction for hashpack - you need to use Hashgraph SDK.
Example of transaction signed by hashpack signer: https://github.com/Hashpack/hashconnect#usage-1
