### ISSUE TITLE
Not able to continue with executing smart contract

### ISSUE THREAD

**Issue by layinka** [Hashpack/hashconnect#109]
Hi,
i am trying to use hashconnect to sign a contractexecute transaction.But i am stuck at the Approve button i.e. nothinghappens when i click approve

![image](https://user-images.githubusercontent.com/629572/168482635-57049a61-001d-40d8-9622-f9ae23ba0d06.png)

Please what can  i do?

**Comment by teacoat** [comment]
@layinka please provide a screenshot of the dev tool console if you are still encountering this
