### ISSUE TITLE
Signing and Sending Transaction with ContractExecuteTransaction Error

### ISSUE THREAD

**Issue by mojowlekaz** [Hashpack/hashconnect#128]
Here is my Code

async function run() {
  
	let saveData = {
		topic: "",
		pairingString: "",
		privateKey: "",
		pairedWalletData: null,
		pairedAccounts: [],
	};
	let appMetadata = {
		name: "Hedera dApp Days",
		description: "Let's buidl a dapp on Hedera",
		icon: "https://raw.githubusercontent.com/ed-marquez/hedera-dapp-days/testing/src/assets/hederaLogo.png",
	};
  let contractId = ContractId.fromString("0.0.47907889");
  let accountId = "0.0.47905112"
  const privateKey = PrivateKey.fromString("302e020100300506032b657004220420341b71552663fe46c2cec11d71dda6a5f804e704760f7e625ba59165a56d1a59");

	let hashconnect = new HashConnect();

  const provider = hashconnect.getProvider('testnet',   saveData.topic,  accountId)
  const signer = hashconnect.getSigner(provider)
  let balance = await provider.getAccountBalance(accountId)
  const stakeTx  = await new ContractExecuteTransaction() 
  .setContractId(contractId)
  .setGas(500000)
  .setPayableAmount(50)
  .setFunction("stakeTokens")
  .freezeWithSigner(signer);
    const result = await stakeTx.executeWithSigner(signer)
   console.log(result)

}
when i run this, it gives me an error "Error: SimpleCrypto object MUST BE initialised with a SECRET KEY."

**Comment by teacoat** [comment]
You are not initializing hashconnect - please read docs

**Comment by mojowlekaz** [comment]
I did initialise Hashconnect

You can send me a link to that if I'm getting something wrong.

**Comment by teacoat** [comment]
You are literally not calling .init()

**Comment by mojowlekaz** [comment]
Oh..

I did that and I'm not sure what the error is about, could you show me how
it'll be written properly?

**Comment by teacoat** [comment]
read the docs

**Comment by steffanjensen** [comment]
> read the docs

Top the worst response I have ever seen on github..

great job

**Comment by teacoat** [comment]
> great job

Thank you

**Comment by steffanjensen** [comment]
Fixed it by following the examples:
https://github.com/Hashpack/hashconnect/tree/main/example/dapp

Still the documentation is lacking.
