### ISSUE TITLE
React Demo is using outdated version - Example app also uses outdated version

### ISSUE THREAD

**Issue by jdaly13** [Hashpack/hashconnect#174]
In the README there is a link to an example [React Integration](https://github.com/rajatK012/hashconnectWalletConnect) - I tried using this code not realizing this code is outdated and different from what you install using `npm i hashconnect` - Either please update README to reflect this or remove the link as it's using an outdated version of the package.  The version being used is 0.1.10 when the current version is 0.2.4

Also the example Angular app within the repo doesn't use the latest build from the library - This is a bug instead of hardcoding the version of hashconnect in the package.json which is 0.2.3 it should reflect the latest build version.  You can easily do this by just running the build script in the lib directory and have all your examples use the latest build version.

The example app and the current demo page - https://hashpack.github.io/hashconnect/
have a bug when your hashpack wallet has multiple accounts - it seems to be fixed when upgrading your version to 0.2.4

<img width="582" alt="Screenshot 2023-02-22 at 11 57 00 AM" src="https://user-images.githubusercontent.com/1916496/220714903-72799182-9e36-4f3e-a7df-9107ab97753f.png">

**Comment by samuelnihoul** [comment]
also the React demo does not work at all. Try to refresh the page and you will see.
