### ISSUE TITLE
any one Help me what is this issuer??? 

### ISSUE THREAD

**Issue by shubhampra156565** [Hashpack/hashconnect#175]
SimpleCrypto.ts:35 Uncaught (in promise) Error: SimpleCrypto object MUST BE initialised with a SECRET KEY.
    at new SimpleCrypto (SimpleCrypto.ts:35:1)
    at MessageUtil.encrypt (message-utils.ts:77:1)
    at MessageUtil.prepareSimpleMessage (message-utils.ts:33:1)
    at HashConnect.sendTransaction (hashconnect.ts:283:1)
    at HashConnectSigner.call (signer.ts:95:1)
    at TransferTransaction.executeWithSigner (Executable.js:490:1)
    at sendTrasaction (signtnx.js:14:1)
    at async onClick (App.js:134:1)
SimpleCrypto @ SimpleCrypto.ts:35
encrypt @ message-utils.ts:77
prepareSimpleMessage @ message-utils.ts:33
sendTransaction @ hashconnect.ts:283
call @ signer.ts:95
executeWithSigner @ Executable.js:490
sendTrasaction @ signtnx.js:14
await in sendTrasaction (async)
callCallback @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:4291
executeDispatch @ react-dom.development.js:9041
processDispatchQueueItemsInOrder @ react-dom.development.js:9073
processDispatchQueue @ react-dom.development.js:9086
dispatchEventsForPlugins @ react-dom.development.js:9097
(anonymous) @ react-dom.development.js:9288
batchedUpdates$1 @ react-dom.development.js:26140
batchedUpdates @ react-dom.development.js:3991
dispatchEventForPluginEventSystem @ react-dom.development.js:9287
dispatchEventWithEnableCapturePhaseSelectiveHydrationWithoutDiscreteEventReplay @ react-dom.development.js:6465
dispatchEvent @ react-dom.development.js:6457
dispatchDiscreteEvent @ react-dom.development.js:6430

**Comment by JubaStriker** [comment]
I am having same problem sending transaction, how to solve this?
