### ISSUE TITLE
Excessive 'Failed to parse source map' Warnings

### ISSUE THREAD

**Issue by a-ridley** [Hashpack/hashconnect#180]
Hashconnect currently generates a significant number of "Failed to parse source map from ..." warnings in the console. These warnings flood the console output and make it difficult to determine if there are actual code issues or if the warnings are unrelated. This creates confusion and hinders the debugging process and creates unnecessary warnings that can cause errors in CI pipelines.

**Expected Behavior:**
There should be no "Failed to parse source map" warnings

**Comment by samuelnihoul** [comment]
Also source maps would be great.
