### ISSUE TITLE
Decryption error when connecting wallet.

### ISSUE THREAD

**Issue by pawelzygmuntowski** [Hashpack/hashconnect#185]
When attempting to connect to a local wallet using `hashconnect.connectToLocalWallet();`, I am getting a decryption error. The error is as follows:
`Error: Invalid encrypted text received. Decryption halted.
    at SimpleCrypto3._decrypt`
I am getting this error not only in my local implementation but in the demo: https://hashpack.github.io/hashconnect/
here as well. Same error. 
I tried making a new wallet from scratch. It didn't help.
Will this be fixed anytime soon?

**Comment by teacoat** [comment]
Please try upgrading to hashconnect v0.2.9

**Comment by pawelzygmuntowski** [comment]
Unfortunately I'm already on v0.2.9. From what I can see it uses the newest version of simple-crypto-js as well. So not sure what could be wrong, as it is literally a new account and wallet (I tried with a few accounts and wallets, all got the same error.

**Comment by pawelzygmuntowski** [comment]
Oh yeah, thank you for this specific info. When I used 4.1.1 exactly as the resolution it connected for now. Hope you guys can manage the fix soon, in the meantime this should work.
