### ISSUE TITLE
Wallet Agnostic option

### ISSUE THREAD

**Issue by jaycoolslm** [Hashpack/hashconnect#192]
At the moment, calling `hashconnect.init()` on page load will cause the HashPack wallet to pop up. 

I propose having a boolean / enum argument in the .init() method which gives devs the option to disable this feature and instead initially pop up with the wallet connect modal

Appreciate that the wallet connect modal doesn't currently have any hedera wallets on it... so maybe this is a feature for after that!

**Comment by teacoat** [comment]
We have disabled the hashpack popup during init, and will be working on the wallet list in the modal stuff
