### ISSUE TITLE
Token transaction do not return any event

### ISSUE THREAD

**Issue by FrancescoGrazioso** [Hashpack/hashconnect#33]
Using React, i'm trying to execute a token transfert using Hedera Token Service.
When i send the transaction to HashConnect the wallet prompts me to approve the transaction, but after that nothing happens.
Here's my code:

`export async function buyRTTToken(token, trsuaryAccountId,reciverAccountId) {
    const client = hederaClient();
    let transaction : TransferTransaction = await new TransferTransaction();
    transaction.addTokenTransfer(token.tokenId, trsuaryAccountId, -10);
    transaction.addTokenTransfer(token.tokenId, reciverAccountId, 10);
    transaction.freezeWith(client);

    await sendTransaction(transaction, reciverAccountId);
}`

`export async function sendTransaction(tx: Transaction, signignAccount: string) {
    let transactionBytes: Uint8Array = tx.toBytes();

    const transaction: MessageTypes.Transaction = {
        topic: saveData.topic,
        byteArray: transactionBytes,
        metadata: {
            accountToSign: signignAccount,
            returnTransaction: false
        }
    }

    await hashconnect.sendTransaction(saveData.topic, transaction)

    hashconnect.transactionResponseEvent.once((data) => {
        console.log("transaction response", data)
    })
}`

The following code aims to let the reciving user to sign the transaction and to pay for the fees of tranfer, since he is requesting token from the tresuary account

**Comment by teacoat** [comment]
@FrancescoGrazioso Could you provide a screenshot of the console after clicking "Approve" in the demo wallet? It should display "SUCCESS" after a few moments, or throw an error if execution failed.

**Comment by teacoat** [comment]
Or - this could be happening because the token you are trying to transfer is not associated to the account

**Comment by FrancescoGrazioso** [comment]
The transaction to associate the token to the wallet account has the same problem, i'll attach the console on the approving transaction. 
The problem is the same, i got no response from the event handler and the console/wallet do not display any "SUCCESS" message.

The following is the code that i'm using to approve the transaction 

`
export async function associateTokenWithAccount(token, accountId) {
    const client = hederaClient();
    let transaction = await new TokenAssociateTransaction();
    transaction.setAccountId(accountId);
    transaction.setTokenIds([token.tokenId]);
    transaction.freezeWith(client);

    await sendTransaction(transaction, accountId);
}
` 

`
export async function sendTransaction(tx: Transaction, signignAccount: string) {
    let transactionBytes: Uint8Array = tx.toBytes();

    const transaction: MessageTypes.Transaction = {
        topic: saveData.topic,
        byteArray: transactionBytes,
        metadata: {
            accountToSign: signignAccount,
            returnTransaction: false
        }
    }

    await hashconnect.sendTransaction(saveData.topic, transaction)

    hashconnect.transactionResponseEvent.once((data) => {
        console.log("transaction response", data)
    })
}
![console on approving token](https://user-images.githubusercontent.com/40018163/147272889-ff23d30f-3ced-415e-8adf-11070c694252.png)

`

**Comment by teacoat** [comment]
Yes so the demo wallet doesn't support the token associate function yet - it's still very much a WIP but I will prioritze adding token association.

Your events are going through fine, the wallet just doesn't have the UI to handle it yet!

**Comment by FrancescoGrazioso** [comment]
Ok thanks, i'll close the issue when you'll release the new version of the wallet

**Comment by teacoat** [comment]
Sounds good - I'll tag you when its ready :)

**Comment by teacoat** [comment]
@FrancescoGrazioso I've updated the demo wallet to support token associate/disassociate
![image](https://user-images.githubusercontent.com/3913019/147294975-862927fc-5b6b-4553-90c4-6cddae11de90.png)

**Comment by teacoat** [comment]
Keep an eye on the console when using it - errors such as "TOKEN_ALREADY_ASSOCIATED" aren't handled by the demo wallet yet

**Comment by FrancescoGrazioso** [comment]
Still nothing from the console, on every transaction i try.
I tried:

- token association
- token dissociation
- token transfert

I'll attach some screen
![dissociate](https://user-images.githubusercontent.com/40018163/147365768-4ecfdad4-b95b-46b2-9b51-b0bdd39e69f1.png)
![dissociate-code](https://user-images.githubusercontent.com/40018163/147365769-502fab14-8038-421c-8db7-99b7a53bd188.png)
![dissociate-console](https://user-images.githubusercontent.com/40018163/147365770-9d5a138f-feee-4c41-8e0e-5b6a5a590825.png)

**Comment by teacoat** [comment]
It looks like you're not listening for another event in this token disassociation function - 
![image](https://user-images.githubusercontent.com/3913019/147370222-10d99085-887c-403d-9ef6-5f04b898e5b9.png)

Listen for a transactionResponseEvent in here!

Send a message to me (pluto) on discord if you want to work through this in real time!

**Comment by teacoat** [comment]
Hmmm that looks to me like it should work - can you reach out to me (pluto) on discord?

**Comment by teacoat** [comment]
There was a bug in the demo where errors werent returning correctly - if you try now both the success and error transaction response events should fire - here is the log from the demo dapp, you can see both transaction responses there!

![image](https://user-images.githubusercontent.com/3913019/147372399-71e45bc5-3aa2-472f-9692-144538712171.png)

**Comment by FrancescoGrazioso** [comment]
It is giving me now the following error
![error_wallet](https://user-images.githubusercontent.com/40018163/147386133-9e1f5700-ead8-4bdd-baaf-e658c2a9b0fc.png)

I reached you on discord

**Comment by FrancescoGrazioso** [comment]
The problem was in the way i was freezing the transaction, with the new code it works!

![image](https://user-images.githubusercontent.com/40018163/147407490-ebbd5d41-bcb7-457d-8eaa-728c9d33f505.png)
