### ISSUE TITLE
Bad `prepareSimpleMessage` return type?

### ISSUE THREAD

**Issue by 3Nigma** [Hashpack/hashconnect#45]
It [currently returns a buffer/uint8array](https://github.com/Hashpack/hashconnect/blame/aad8d526f41cdbd641d6c72e6070a0f0cbcd8a77/lib/src/message/message-utils.ts#L30) even though there are places, mostly around send-transactions region where the result is expected to have an id.

Examples of such places: [here](https://github.com/Hashpack/hashconnect/blob/main/lib/src/hashconnect.ts#L124), [here](https://github.com/Hashpack/hashconnect/blob/main/lib/src/hashconnect.ts#L132) and [here](https://github.com/Hashpack/hashconnect/blob/main/lib/src/hashconnect.ts#L142) + others in the same file.

What's the intent of that `msg.id` and is it still relevant or can it be cleaned out and we are not expected to have anything returned following a `sendTransaction` operation?

**Comment by teacoat** [comment]
Hey @3Nigma sorry for the late reply, been focused on stability updates.

ID is used to denote which messages responses are in response to, for example the acknowledge event returns the message ID of what is being acknowledged:

![image](https://user-images.githubusercontent.com/3913019/154605775-9ae3f14f-5788-4ea2-8c03-9a0118235cec.png)

**Comment by teacoat** [comment]
I don't think this is an issue anymore so I'm going to close it
