### ISSUE TITLE
Wallet unsubscribed event

### ISSUE THREAD

**Issue by teacoat** [Hashpack/hashconnect#69]
In the case of removing a pairing from a wallet, an event should be sent to dapps informing them that the wallet is no longer subscribed to the topic and to handle appropriately

**Comment by scalemaildev** [comment]
It would also be nice if we had a method of verifying whether the dapp is still approved by the wallet. Either as a unique function or part of the connection method's return.

**Comment by hashaxis** [comment]
+1 

Many users have written in that they were unable to transact. Upon investigation it would appear that their wallets became disconnected as some point but our dApp had no way to notify them of this and presented as if the wallet was still connected. The only remedy being to advise the users to disconnect and reconnect their wallets.

**Comment by pwoosam** [comment]
There should be a way to verify that a wallet is actively connected. Right now hashconnect can tell the dapp and the wallet if it is actively connected to the hashconnect websocket, but does not indicate if both the wallet and dapp are both currently in communication with eachother. Knowing that both the dapp and wallet are active and paired would benefit the dapp and user experience.

**Comment by teacoat** [comment]
The complications with this arise when you take into consideration that its a client side library and simply not having the app open (for example the web/mobile versions) would be considered 'not connected' by a dapp, when really the user just doesnt have it open. We are still exploring the most elegant way to handle this.
