### ISSUE TITLE
Assistance with `HashConnect.connectToLocalWallet`

### ISSUE THREAD

**Issue by 3Nigma** [Hashpack/hashconnect#73]
I can't make this to work and it looks like the docs are not in sync with the code so I'm not quite sure what's happening here.

[Code](https://github.com/Hashpack/hashconnect/blob/7239e2b3112820933ee9df361e77da52e1ddc460/lib/src/hashconnect.ts#L286):
![image](https://user-images.githubusercontent.com/210908/157403471-f30081aa-0ad4-429e-b320-ef8d30c3e1aa.png)

[Docs](https://github.com/Hashpack/hashconnect/blob/main/README.md):
![image](https://user-images.githubusercontent.com/210908/157403665-6d02990d-481d-41a0-89bb-73157eee5b27.png)

Is there a working example somewhere?

**Comment by teacoat** [comment]
> Before we close this ticket, I was wondering to ask the reason for having the `extensionMetadata` be delivered through the `connectToLocalWallet` method? Is it to support multiple dApps from the same page?

The reason for this is eventually we plan to allow other wallets to implement hashconnect, and this metadata will allow the dapp to display different options for the user to select if they have more than one compatible extension installed
