### ISSUE TITLE
Support FileAppendTransaction

### ISSUE THREAD

**Issue by 3Nigma** [Hashpack/hashconnect#79]
Currently, we get back `Error: There was an issue while signing the request: HASHCONNECT_TRANSACTION_TYPE_NOT_SUPPORTED` when trying to send a `FileAppendTransaction`. `FileCreateTransaction` is supported, so it would be nice if this was supported as well.

I know this is not a priority, but it would be nice if this was be available so that [strato's live-editor docs > guides > contracts](https://hsj-docs.buidlerlabs.com/markdown/guides/entities/contract) would fully work since most of the contract bytecodes exceeded the current limit of 1024 bytes per transaction which require second subsequent append-transaction calls.

**Comment by teacoat** [comment]
Will be in the next hashpack release!
