### ISSUE TITLE
TransferTransaction token amount view (question)

### ISSUE THREAD

**Issue by wwwtsv** [Hashpack/hashconnect#80]
Hello! Could you explain me what did I do wrong? I'm trying to send test token (0.0.3084461) with Dapp demo. When I'm sending two tokens
<img width="540" alt="Screenshot 2022-03-23 at 11 30 47" src="https://user-images.githubusercontent.com/42433438/159658219-44d3ad33-09d9-485d-bc1e-c576ec9692b3.png">

In Hashpack I see that I received **0** tokens and then I got an error: TRANSFERS_NOT_ZERO_SUM_FOR_TOKEN

<img width="1106" alt="Screenshot 2022-03-23 at 11 35 41" src="https://user-images.githubusercontent.com/42433438/159658837-01ba6677-182b-42ea-b1da-f2fc6530b45e.png">
<img width="836" alt="Screenshot 2022-03-23 at 11 43 38" src="https://user-images.githubusercontent.com/42433438/159658867-c673096e-4f4f-4cde-804a-53d06627e1fc.png">

**Comment by teacoat** [comment]
You need to do two transfers, one subtracting tokens from the treasury account and one adding them to the receiving account so that the net sum of tokens transferred is zero. The UI for this could be a bit nicer to be honest.
