### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by joelviel** [Hashpack/hashconnect#81]
Running the example from https://www.npmjs.com/package/hashconnect with node version 16.14.12 

`const { HashConnect } = require( 'hashconnect');
let hashconnect = new HashConnect();

let appMetadata = {
    name: "dApp Example",
    description: "An example hedera dApp",
    icon: "https://absolute.url/to/icon.png"
}

hashconnect.init(appMetadata)
.then(initData => {
    let privateKey = initData.privKey
    console.log("privateKey", privateKey)
})`

xyz\hconnect\node_modules\hashconnect\dist\hashconnect.js:43
                if (window)
                ^

ReferenceError: window is not defined
    at HashConnect.<anonymous> (xyz\hconnect\node_modules\←[4mhashconnect←[24m\dist\hashconnect.js:43:17)
    at Generator.next (<anonymous>)
    at fulfilled (xyz\node_modules\←[4mtslib←[24m\tslib.js:110:62)

**Comment by teacoat** [comment]
hashconnect is meant to be used client side, we do not officially support server side at the moment
