### ISSUE TITLE
TypeError: hashconnect.authenticate is not a function

### ISSUE THREAD

**Issue by joelviel** [Hashpack/hashconnect#91]
following readme page to test authenticate
const resp = await hashconnect.authenticate(topic, accountId)

TypeError: hashconnect.authenticate is not a function

How to access authenticate method from 
const { HashConnect } = require("hashconnect")

**Comment by teacoat** [comment]
We have recently released an update for authenticate(), please try again

https://github.com/Hashpack/hashconnect#authenticate
