### ISSUE TITLE
Transaction stuck on execution / duplicated trasnaction id if previous success message has not been cleared

### ISSUE THREAD

**Issue by KilianB** [Hashpack/hashconnect#94]
These are actual two issues which might have the same root case

1. Approve a transaction but do not clear the success message:

![image](https://user-images.githubusercontent.com/9025925/162377837-f2b41ae6-29cc-4ee7-b9da-c878c430dcb9.png)

2. Make a second request. Now clear the message

![image](https://user-images.githubusercontent.com/9025925/162377918-519782ca-7220-404e-876e-a20549dc3f32.png)

3. Approve the new transaction:
![image](https://user-images.githubusercontent.com/9025925/162378005-8124bc14-38a5-4d49-b91f-8c94748dcc30.png)

-----------

If waiting a longer time between step 1 and 2 hashpack simply is stuck on execution. Maybe this happens when the wallet would lock itself otherwise?

![image](https://user-images.githubusercontent.com/9025925/162376044-dca29f14-2388-45d6-aaa8-36eb032ac9d3.png)

**Comment by teacoat** [comment]
I have fixed both of these issues last night, will be in the next hashpack release!
